sudo: required

language: node_js

node_js:
  - 'node'
  - 'lts/*'

before_script:
  # Install meteor
  - curl https://install.meteor.com | /bin/sh
  # Add meteor to path (instead of asking for sudo in the Travis container)
  # We can then use the faster container infrastructure - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
  - export PATH=$HOME/.meteor:$PATH

script:
  - meteor npm install --save bcrypt

notifications:
  email:
    on_failure: change

after_success: 'npm run coverage'

cache:
  directories:
    - node_modules
    - ~/.meteor
    - .meteor/local
